export const fontList = {
  list: [
    'Aktuelle',
    'CollegiateFLF',
    'Arial Narrow',
    'Krinkes Regular',
    'Bulletto Killa',
    'CollegiateBorderFLF',
    'Athletic',
    'CollegiateBlackFLF',
    'CollegiateOutlineFLF',
    'SignPainter HouseScript',
    'Amarillo',
    'CollegiateInsideFLF',
    'Arial',
    'Typewriter-Serial',
    'College',
    'Brannboll F',
    'Superstar M54',
    'Arial Black',
    'VARSITY',
    'United Sans Bold',
    'United Serif Heavy',
    'United Serif Bold'
  ]
}

  /*
CollegiateFLF,
Arial Narrow,
Krinkes Regular PERSONAL USE,
Bulletto Killa, CollegiateBorderFLF,
Athletic,
CollegiateBlackFLF,
TKD HomeRun Script,
CollegiateOutlineFLF,
SignPainter HouseScript,
Amarillo,
Aktuelle,
CollegiateInsideFLF,
Arial,
Montserrat,
Typewriter-Serial,
College,
Brannboll F PERSONAL USE ONLY,
Superstar M54 MT&quot,
Arial Rounded MT,
Arial Black,
Varsity,
United Sans SmCd Bd SmCd,
United Serif SmCd Hv,
United Serif SmCd Bd,
*/
